#! /usr/local/bin/bash

# Count different lines that match match a pattern

IFS=$'\n'
key=$1
for line in `ack $key rules_report.txt|sort|uniq`
do
  count=(`ack "$line" rules_report.txt|wc -l`)
  echo -e "$count\t$line"
done