#! /usr/local/bin/bash

# Count different lines that match match a pattern

IFS=$'\n'
key=$1
if [[ $key == '' ]]
then
  key=BKCR
fi

for line in `ack $key rules_report.txt|sort|uniq`
do
  count=(`ack -c "$line" rules_report.txt`)
  printf "%'d cases:\t%s\n" $count $line
  if [[ $SUMMARY ]]
  then
    echo -e "----------------------------------------------------------------------"
    examples=`ack -B 4 -A 1 $line rules_report.txt`
    echo "$examples"
    echo
  fi
done