#! /usr/local/bin/bash

# Count different lines that match match a pattern

key=$1
if [[ $key == '' ]]
then
  key=BKCR
fi

IFS=$'\n'
lines=`ack $key rules_report.txt|sort|uniq`

for line in $lines
do
  count=`ack -c "$line" rules_report.txt`
  echo -e "$count\t$line" >> $$_counts
done

for line in `cat $$_counts | sort -k1 -n`
do
  echo $line
  if [[ $SUMMARY ]]
  then
    echo -e "----------------------------------------------------------------------"
    text=`echo "$line" | cut -f 2-`
    examples=`ack -B 4 -A 1 "$text" rules_report.txt`
    echo "$examples"
    echo
  IFS=$'\n'
  fi
done
rm $$_counts
